import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import './styles.css';
//import Head from "next/head";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/images/favicon.ico" type="image/x-icon"/>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="A site to shuffle every shuffle" />
        <meta property="og:title" content="Unshuffled" />
        <meta property="og:description" content="A site to shuffle every shuffle" />
        <meta property="og:image" content="/images/Unshuffled_Preview.png" />
        <meta property="og:url" content="https://unshuffled.net" />
        <meta property="og:type" content="website" />
        <title>Shuffle please</title>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
